name: Playwright Tests
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    playwright:
        name: 'Playwright Tests'
        runs-on: ubuntu-latest
        env:
            BASE_URL_UI: https://www.tui.nl
            TAG: '@smoke'
        container:
            image: mcr.microsoft.com/playwright:v1.56.1-noble
        steps:
            - uses: actions/checkout@v5

            - name: Install unzip
              run: apt-get update && apt-get install unzip -y

            - name: Load secrets
              uses: 1password/load-secrets-action@v3
              with:
                  export-env: true

            - uses: actions/setup-node@v6
              with:
                  node-version: lts/*

            - name: Install dependencies
              run: npm install

            - name: Print ENV Variables
              run: |
                  echo "Repository: $GITHUB_REPOSITORY"
                  echo "Workflow: $GITHUB_WORKFLOW"
                  echo "Run ID: $GITHUB_RUN_ID"
                  echo "Commit SHA: $GITHUB_SHA"
                  echo "CURRENT_DATETIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
                  env

            - name: Run tests
              run: npm test

            - name: Upload test results and videos
              uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: playwright-results
                  path: |
                      playwright-report/
                      test-results/
                  retention-days: 30

            - name: Upload HTML report
              uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
